#!/bin/bash
if [[ $1 == "-y" ]]; then
  python3 /usr/share/felis/felis.py $1

elif [[ $1 == "klon" ]]; then
  python3 /usr/share/felis/felis.py $1 $2

elif [[ $1 == "-mp3" ]]; then
  python3 /usr/share/felis/felis.py $1 $2

elif [[ $1 == "-mp4" ]]; then
  python3 /usr/share/felis/felis.py $1 $2

elif [[ $1 == "-g" ]]; then
  python3 /usr/share/felis/felis.py $1

elif [[ $1 == "-s" ]]; then
  python3 /usr/share/felis/felis.py $1

elif [[ $1 == "-git" ]]; then
  python3 /usr/share/felis/felis.py $1

elif [[ $1 == "-depo" ]]; then
  python3 /usr/share/felis/felis.py $1

else
  python3 /usr/share/felis/felis.py -y
fi
